### ISSUE TITLE
Multiple ratings

### ISSUE THREAD

**Issue by tiadear** [1002915/filmCMS#118]
Users are able to input multiple ratings for a movie

**Comment by Amurphy28** [comment]
can only rate once but can users still click

**Comment by Amurphy28** [comment]
also overlord has a bind parameter issue as the value in the rating input is only picking up as null

**Comment by Amurphy28** [comment]
issue sloved using commit: b5043a9ae15106f5acec75f22a4e82b53b7b4bfc
