### ISSUE TITLE
Double click on submits

### ISSUE THREAD

**Issue by calliePepper** [1002915/filmCMS#140]
All submits I have noticed can be double clicked on, ultimately sending the same data twice

**Comment by 1002915** [comment]
Guys, if any of your forms are able to be submitted twice (anything really that updates the database that posts to a file I guess?) you can add this to the submit button's html:

`onclick="this.disabled=true;this.value='Submitting...'; this.form.submit();"`

Have a look at the login button on headercontent.php if you wanna see what I did. If anyone sees any huge problems by doing it this way, let me know and I'll find another way.

**Comment by 1002915** [comment]
I've been told the above way isn't the best way to go about it. Ideas?

**Comment by tiadear** [comment]
new film, edit film, profile, login need the following the function and code added:

jQuery.fn.preventDoubleSubmission = function() {
   $(this).on('submit',function(e){
    var form = $(this);
    if (form.data('submitted') === true) {
         e.preventDefault();
     } else {
        form.data('submitted', true);
    }
   });

   return this;
};

form.on('submit', function(e){
        e.preventDefault();
    $('form').preventDoubleSubmission();
});

**Comment by 1002915** [comment]
fixed login also.
