### ISSUE TITLE
Search results thumbnail doesn't display.

### ISSUE THREAD

**Issue by 1002915** [1002915/filmCMS#160]
It's currently expecting the uploaded content to be in the index folder. Code needs to insert the film uploaders id. It needs to read:

`<div class="film_cover_image" style="background-image:url('+"'uploads/"+value.user_id+'/'+value.cover_image+"'"+')">`

instead of 

`<div class='film_cover_image' style='background-image:url("+value['cover_image']+");'>`

**Comment by Amurphy28** [comment]
issue solved via 273e5890dcc2278508452ed9d58bc3c6a6bb1a16 commit
