### ISSUE TITLE
Errors when submitting changes on editfilm page

### ISSUE THREAD

**Issue by 1002915** [1002915/filmCMS#161]
`Notice: Undefined variable: data in /Applications/MAMP/htdocs/filmCMS/overlord.php on line 677
null
Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/filmCMS/overlord.php:677) in /Applications/MAMP/htdocs/filmcms/formsubmit.php on line 3`

**Comment by tiadear** [comment]
form is now submitted via ajax - fixed with formsubmit error
