### ISSUE TITLE
Sign up -> Register flow

### ISSUE THREAD

**Issue by calliePepper** [1002915/filmCMS#172]
If I enter an email on the sign up page and then click register, the email should be in the register input already.

**Comment by 1002915** [comment]
I'm not sure I fully understand what you mean? could you elaborate?

**Comment by tiadear** [comment]
I think she means that on the home page when you first click login you can fill in all your fields and then press sign-up or login. If you press sign up it should remember your email address and prefill it in the email field on the sign-up box.

**Comment by 1002915** [comment]
Okay got it.

**Comment by 1002915** [comment]
Fixed. Used Jquery to pre fill on keyup for all forms.
